"""Общие безопасные примитивы управления KVN VPN."""

from .apply import (
    ApplyAction,
    ChangeSet,
    RenderResult,
    SERVICE_CAPABILITIES,
    build_change_set,
    merge_service_change,
)
from .client_export import (
    ClientExportPolicy,
    ClientExportValidationError,
    ExportSection,
    SubscriptionIpReadiness,
    client_connection_host,
    normalize_client_export_state,
    render_export_document,
    subscription_ip_readiness,
    validate_public_ipv4,
    with_client_export_policy,
)
from .core import (
    CURRENT_STATE_SCHEMA_VERSION,
    ProjectPaths,
    StateMigrationError,
    StateValidationError,
    migrate_state,
    redact_secrets,
    state_schema_version,
    validate_state_shape,
)
from .cli import (
    add_client_export_parsers,
    atomic_write_private,
    serialize_user_export,
)
from .export_bundle import (
    ALLOWED_ARTIFACTS,
    ExportBundleError,
    UserExportBundle,
    build_user_export_bundle,
)
from .exports import RENDERER_NAMES, RendererRegistry
from .state import (
    JsonStateStore,
    StateLockTimeout,
    StateRevisionConflict,
    atomic_write_json,
    atomic_write_text,
    state_revision,
)
from .services import (
    COMPOSE_SERVICE_ORDER,
    DOCKER_SERVICE_ORDER,
    HOST_SERVICE_ORDER,
    OPERATOR_SERVICE_ORDER,
    EffectiveServicePlan,
    configured_service_preferences,
    effective_service_plan,
    service_preference,
)
from .runtime import ApplyResult, VerificationResult, host_tunnel_action, normalize_apply_report

__all__ = [
    "ApplyAction",
    "ApplyResult",
    "ALLOWED_ARTIFACTS",
    "ChangeSet",
    "ClientExportPolicy",
    "ClientExportValidationError",
    "ExportSection",
    "ExportBundleError",
    "COMPOSE_SERVICE_ORDER",
    "CURRENT_STATE_SCHEMA_VERSION",
    "DOCKER_SERVICE_ORDER",
    "EffectiveServicePlan",
    "HOST_SERVICE_ORDER",
    "JsonStateStore",
    "RenderResult",
    "RENDERER_NAMES",
    "RendererRegistry",
    "OPERATOR_SERVICE_ORDER",
    "ProjectPaths",
    "SERVICE_CAPABILITIES",
    "StateLockTimeout",
    "StateMigrationError",
    "StateRevisionConflict",
    "StateValidationError",
    "SubscriptionIpReadiness",
    "UserExportBundle",
    "VerificationResult",
    "atomic_write_json",
    "atomic_write_private",
    "add_client_export_parsers",
    "atomic_write_text",
    "build_change_set",
    "build_user_export_bundle",
    "client_connection_host",
    "configured_service_preferences",
    "effective_service_plan",
    "host_tunnel_action",
    "merge_service_change",
    "migrate_state",
    "normalize_client_export_state",
    "normalize_apply_report",
    "render_export_document",
    "redact_secrets",
    "service_preference",
    "serialize_user_export",
    "state_revision",
    "state_schema_version",
    "subscription_ip_readiness",
    "validate_public_ipv4",
    "validate_state_shape",
    "with_client_export_policy",
]
